src/main/java/com/museum/model/Exhibit.java
package com.museum.model;

import com.museum.model.Enums.State;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.*;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import java.io.Serializable;

@Entity
@XmlRootElement(name = "exhibit")
@Table(name = "exhibit")
public class Exhibit implements Serializable,Exhibitble {
    @Id
    @GeneratedValue
    private Integer id_exhibit;

    @Size(min = 3, max = 20)
    private String title;

    @Size(min = 3, max = 255)
    private String about;

    @NotEmpty
    private String category;

    @NotEmpty
    private String image;

    @Enumerated(EnumType.STRING)
    private State state = State.onStock;

    @OneToOne
    @PrimaryKeyJoinColumn
    private ExportExhibit exportExhibit;

    @OneToOne
    @PrimaryKeyJoinColumn
    private StoredExhibit storeExhibit;

    @OneToOne
    @PrimaryKeyJoinColumn
    private MuseumExhibit museumExhibit;

    public Exhibit() {
    }

    public StoredExhibit getStoreExhibit() {
        return storeExhibit;
    }

    public void setStoreExhibit(StoredExhibit storeExhibit) {
        this.storeExhibit = storeExhibit;
    }

    public MuseumExhibit getMuseumExhibit() {
        return museumExhibit;
    }

    public void setMuseumExhibit(MuseumExhibit museumExhibit) {
        this.museumExhibit = museumExhibit;
    }

    public ExportExhibit getExportExhibit() {
        return exportExhibit;
    }

    public void setExportExhibit(ExportExhibit exportExhibit) {
        this.exportExhibit = exportExhibit;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    @Override
    public Integer getIdExhibit() {
        return id_exhibit;
    }

    @Override
    public Integer getLocationValue() {
        return 0;
    }
    @XmlElement
    public void setId_exhibit(Integer id_exhibit) {
        this.id_exhibit = id_exhibit;
    }

    public String getTitle() {
        return title;
    }

    @XmlElement
    public void setTitle(String title) {
        this.title = title;
    }

    public String getAbout() {
        return about;
    }

    @XmlElement
    public void setAbout(String about) {
        this.about = about;
    }

    public String getCategory() {
        return category;
    }

    @XmlElement
    public void setCategory(String category) {
        this.category = category;
    }

    public State getState() {
        return state;
    }

    @XmlElement
    public void setState(State state) {
        this.state = state;
    }

    public Exhibit(String title, String about, String category, String image, State state) {
        this.title = title;
        this.about = about;
        this.category = category;
        this.image = image;
        this.state = state;
    }

    @Override
    public String toString() {
        return "id:" + id_exhibit +
                ", title:" + title +
                ", category:" + category;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;

        if (o == null || getClass() != o.getClass()) return false;

        Exhibit exhibit = (Exhibit) o;

        return new org.apache.commons.lang.builder.EqualsBuilder()
                .append(id_exhibit, exhibit.id_exhibit)
                .append(title, exhibit.title)
                .append(about, exhibit.about)
                .append(category, exhibit.category)
                .isEquals();
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder(17, 37)
                .append(id_exhibit)
                .append(title)
                .append(about)
                .append(category)
                .toHashCode();
    }
}

src/main/webapp/WEB-INF/views/403.jsp
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<html>
<body>
	<h1>HTTP Status 403 - Access is denied</h1>

	<c:choose>
		<c:when test="${empty username}">
			<h2>You do not have permission to access this page!</h2>
		</c:when>
		<c:otherwise>
			<h2>Username : ${username} <br/>You do not have permission to access this page!</h2>
		</c:otherwise>
	</c:choose>

</body>
</html>

src/main/webapp/WEB-INF/views/404.jsp
<!--A Design by W3layouts
Author: W3layout
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>404</title>
    <style type="text/css">
        body{
            font-family:Arial, Helvetica, sans-serif;
        }
        .wrap{
            width:1000px;
            margin:0 auto;
        }
        .logo{
            width:430px;
            position:absolute;
            top:25%;
            left:35%;
        }
        p a{
            color:#eee;
            font-size:13px;
            margin-left:30px;
            padding:5px;
            background:#FF3366;
            text-decoration:none;
            -webkit-border-radius:.3em;
            -moz-border-radius:.3em;
            border-radius:.3em;
        }
        p a:hover{
            color: #fff;
        }
        .footer{
            position:absolute;
            bottom:10px;
            right:10px;
            font-size:12px;
            color:#aaa;
        }
        .footer a{
            color:#666;
            text-decoration:none;
        }

    </style>
</head>
<body>


<div class="wrap">
    <div class="logo">
        <img src="../../resources/styleimages/404.png" alt=""  />
        <!---728x90--->
        <div style="text-align: center;">
           </div>
        <p><a href="/">Go back to Home</a></p>
    </div>
</div>
<div style="text-align: center;">
   </div>

<div class="footer">
    <ul id="copyright">
        <li>&copy; Untitled.</li>
        <li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
        <li>Developed by : <br> <a href="https://vk.com/id86063569">Io</a> and <a href="https://vk.com/id183792251">Ktulhu</a> </li>
    </ul>
</div>
<div style="text-align: center;">
    </div>
</body>
</html>

src/main/webapp/WEB-INF/views/addForm.jsp
<%@ page language="java" contentType="text/html; charset=utf-8"
         pageEncoding="ISO-8859-1" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link href="<c:url value='../../resources/css/style.css' />" rel="stylesheet">
    <link href="<c:url value='../../resources/css/bootstrap.css' />" rel="stylesheet">
    <title>Museum</title>

    <script language="javascript" type="text/javascript"
            src="http://ajax.googleapis.com/ajax/libs/jquery/1.2.6/jquery.min.js"></script>
    <script language="javascript" type="text/javascript"
            src="../../resources/js/Main.js"></script>
</head>

<body>

<div id="header">

    <div id="social">
        <a href="#"><img src="../../resources/styleimages/facebook.png" width="26" height="26" alt="facebook"/></a>
        <a href="#"><img src="../../resources/styleimages/twitter.png" width="26" height="26" alt="twitter"/></a>
        <a href="#"><img src="../../resources/styleimages/linkedin.png" width="26" height="26" alt="linkedin"/></a>
        <a href="#"><img src="../../resources/styleimages/email.png" width="26" height="26" alt="email"/></a>
    </div>

</div>


<ul class="dropdown"><!-- menu -->

    <li><a href="${pageContext.request.contextPath}/">Home</a></li>

    <li><a href="${pageContext.request.contextPath}/gallery">Gallery</a>
        <ul class="sub_menu">
            <li><a>Category</a>
                <ul>
                    <c:forEach items="${categoriesList}" var="category">
                        <li>
                            <a href="${pageContext.request.contextPath}/gallery?sort=category&value=${category}">${category}</a>
                        </li>
                    </c:forEach>
                </ul>
            </li>
            <li><a href="${pageContext.request.contextPath}/gallery?sort=state&value=Exhibition">Exhibition</a></li>
            <li><a href="${pageContext.request.contextPath}/gallery?sort=state&value=On%20Export">On export</a></li>
        </ul>
    </li>
    <!-- end submenu -->
    <li><a href="${pageContext.request.contextPath}/admin/saveUpdate?id=0">NewExhibit</a></li>
    <li><a href="${pageContext.request.contextPath}/admin/exhibitManagement">Admin panel</a></li>
</ul><!-- close menu -->

<div id="galeryWraper">
    <div id="gallery"><!-- gallery -->
        <span class="label label-success">${Success}</span>
        <br/>
        <form:form action="saveUpdate" method="post" class="form-horizontal" modelAttribute="exhibit">
        <form:input id="id_exhibit" path="id_exhibit" type="hidden" value="${exhibit.id_exhibit+0}"/>
        <input type="hidden" id="csrfToken" name="${_csrf.parameterName}"
               value="${_csrf.token}" />
        <div class="row">
            <div class="form-group col-md-12">
                <label class="col-md-3 control-lable" for="Title">Title</label>

                <div class="col-sm-12">
                    <form:input type="text" class="form-control" path="title" name="title" id="Title"
                                value="${exhibit.title}"/>
                    <div class="has-error">
                        <form:errors path="title" class="help-inline"/>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="form-group col-md-12">
                <label class="col-md-3 control-lable" for="about">About</label>
                <div class="col-sm-12">
                    <form:input type="text" class="form-control" id="about" path="about" value="${exhibit.title}"/>


                    <div class="has-error">
                        <form:errors path="about" class="help-inline"/>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-12">
                <label class="col-md-3 control-lable">Category</label>
                <div class="col-sm-12">

                    <c:forEach items="${categoriesList}" var="cat">
                        <div class="radio">
                            <label>
                                <form:radiobutton value="${cat}" path="category"/>${cat}
                            </label>
                        </div>
                    </c:forEach>
                    <div class="has-error">
                        <form:errors path="category" class="help-inline"/>
                    </div>
                </div>
            </div>
        </div>
        <div id="addFormImageSubmitOrganization">
            <div class="form-group">
                <div class="col-sm-offset-0 col-sm-10 submitMargin">
                    <input type="submit" value="Save Exhibit" class="btn btn-primary"/>
                </div>
            </div>

            <form:input id="image_from_list" name="image" type="hidden" value="" path="image"/>

            </form:form>
            <form:form id="forma" modelAttribute="image" target="frame_ajax" action="saveImage?_csrf=${_csrf.token}"
                       enctype="multipart/form-data">
                <div id="uploadPictureOrganization">
                    <input id="UploadFile" name="files[0]" type="file"/>
                    <button class="btn btn-primary" name="Up" value="Upload" onclick="Upload()">Upload</button>
                </div>
            </form:form>
            <iframe name="frame_ajax" src="http://localhost:8080/saveImage" width="0" height="0" style="display:none">
            </iframe>

            <img id="image_container" alt="none load" src=""/>
            <div class="has-error">
                <form:errors path="image" class="help-inline"/>
            </div>

        </div>
    </div>
</div>
<!-- close gallery -->
<div id="footer">

</div>

</body>
</html>

src/main/webapp/WEB-INF/views/changeState.jsp
<%@ page language="java" contentType="text/html; charset=utf-8"
         pageEncoding="ISO-8859-1" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link href="<c:url value='../../resources/css/style.css' />" rel="stylesheet">
    <link href="<c:url value='../../resources/css/bootstrap.css' />" rel="stylesheet">
    <link href="<c:url value='../../resources/css/changeState.css' />" rel="stylesheet">
    <title>Museum</title>

    <script language="javascript" type="text/javascript"
            src="http://ajax.googleapis.com/ajax/libs/jquery/1.2.6/jquery.min.js"></script>
    <script language="javascript" type="text/javascript"
            src="../../resources/js/changeState.js"></script>
</head>

<body>

<div id="header">

    <div id="social">
        <a href="#"><img src="../../resources/styleimages/facebook.png" width="26" height="26" alt="facebook"/></a>
        <a href="#"><img src="../../resources/styleimages/twitter.png" width="26" height="26" alt="twitter"/></a>
        <a href="#"><img src="../../resources/styleimages/linkedin.png" width="26" height="26" alt="linkedin"/></a>
        <a href="#"><img src="../../resources/styleimages/email.png" width="26" height="26" alt="email"/></a>
    </div>

</div>


<ul class="dropdown"><!-- menu -->

    <li><a href="${pageContext.request.contextPath}/">Home</a></li>

    <li><a href="${pageContext.request.contextPath}/gallery">Gallery</a>
        <ul class="sub_menu">
            <li><a>Category</a>
                <ul>
                    <c:forEach items="${categoriesList}" var="category">
                        <li>
                            <a href="${pageContext.request.contextPath}/gallery?sort=category&value=${category}">${category}</a>
                        </li>
                    </c:forEach>
                </ul>
            </li>
            <li><a href="${pageContext.request.contextPath}/gallery?sort=state&value=Exhibition">Exhibition</a></li>
            <li><a href="${pageContext.request.contextPath}/gallery?sort=state&value=On%20Export">On export</a></li>
        </ul>
    </li>
    <!-- end submenu -->
    <li><a href="${pageContext.request.contextPath}/admin/saveUpdate?id=0">NewExhibit</a></li>
    <li><a href="${pageContext.request.contextPath}/admin/exhibitManagement">Admin panel</a></li>
</ul><!-- close menu -->

<div id="galeryWraper">
    <div id="gallery"><!-- gallery -->
        <span class="label label-success">${Success}</span>
        <span>Curent location : ${exhibitInfo.exhibit.state}| ${exhibitInfo.locationDescription}(ID: ${exhibitInfo.locationValue})</span>
        <br/>
        <form action="${pageContext.request.contextPath}/admin/changeState" method="post">
            <input value="${exhibitInfo.exhibit.getIdExhibit()}" name="idExhibit" type="hidden"/>
            <input type="hidden" id="csrfToken" name="${_csrf.parameterName}"
                   value="${_csrf.token}"/>
            <div class="row">
                <div class="form-group col-md-12">
                    <label class="col-md-3 control-lable">State</label>
                    <div class="col-sm-12">
                        <div class="radio">
                            <label for="radioStateOne">exhibition:</label>
                            <input type="radio" id="radioStateOne" name="newState" value="exhibition" onclick="ShowValuesList('museum')" required><br/>
                        </div>
                        <div class="radio">
                            <label for="radioStateTwo">onStock:</label>
                            <input type="radio" id="radioStateTwo" name="newState" value="onStock" onclick="ShowValuesList('stock')"><br/>
                        </div>
                        <div class="radio">
                            <label for="radioStateThree">onExport:</label>
                            <input type="radio" id="radioStateThree" name="newState" value="onExport" onclick="ShowValuesList('export')"><br/>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-12">
                    <label class="col-md-3 control-lable">Value</label>
                    <div class="col-sm-12">

                        <div id="statePagePlaceListContainer">

                                <c:forEach items="${placeList}" var="place">
                                    <div class="radio">
                                    <label for="${place.id_place}">${place.place_name}</label>
                                    <input type="radio" id="${place.id_place}" value="${place.id_place}"
                                           name="idPlace">
                                    </div>
                                </c:forEach>

                        </div>
                        <br/>
                        <div id="statePageOwnersListContainer">
                                <c:forEach items="${ownersList}" var="owner">
                                    <div class="radio">
                                    <label for="${owner.id_owner}">${owner.fio}</label>
                                    <input type="radio" id="${owner.id_owner}" value="${owner.id_owner}"
                                           name="idOwner">
                                    </div>
                                </c:forEach>
                        </div>
                        <br/>
                        <div id="statePageStoresListContainer">
                                <c:forEach items="${storeSectionsList}" var="storeSection">
                                    <div class="radio">
                                    <label for="${storeSection.id_section}">${storeSection.section}:</label>
                                    <input type="radio" id="${storeSection.id_section}"
                                           value="${storeSection.id_section}" name="idSection">
                                    </div>
                                </c:forEach>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-12">
                    <div class="col-sm-12">
                        <input type="submit" value="Update State" class="btn btn-primary"/>
                    </div>
                </div>
            </div>
        </form>
    </div>
    </div>
<!-- close gallery -->
<div id="footer">

</div>

</body>
</html>

src/main/webapp/WEB-INF/views/exhibitManagement.jsp
<%@ page language="java" contentType="text/html; charset=utf-8"
         pageEncoding="ISO-8859-1" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link href="<c:url value='../../resources/css/style.css' />" rel="stylesheet">
    <link href="<c:url value='../../resources/css/modalForm.css' />" rel="stylesheet">
    <link href="<c:url value='../../resources/css/bootstrap.css' />" rel="stylesheet">
    <link href="<c:url value='../../resources/css/jquery.fancybox-1.3.0.css' />" rel="stylesheet">
    <title>${userName}</title>

    <script language="javascript" type="text/javascript"
            src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="../../resources/js/jquery.fancybox-1.3.0.pack.js"></script>
    <script type="text/javascript" src="../../resources/js/jquery.redirect.js"></script>
    <script type="text/javascript" src="../../resources/js/exhibitManagement.js"></script>
</head>

<body>
<div id="header">

    <div id="social">
        <a href="#"><img src="../../resources/styleimages/facebook.png" width="26" height="26" alt="facebook"/></a>
        <a href="#"><img src="../../resources/styleimages/twitter.png" width="26" height="26" alt="twitter"/></a>
        <a href="#"><img src="../../resources/styleimages/linkedin.png" width="26" height="26" alt="linkedin"/></a>
        <a href="#"><img src="../../resources/styleimages/email.png" width="26" height="26" alt="email"/></a>
    </div>

</div>


<ul class="dropdown"><!-- menu -->

    <li><a href="${pageContext.request.contextPath}/">Home</a></li>

    <li><a href="${pageContext.request.contextPath}/gallery">Gallery</a>
        <ul class="sub_menu">
            <li><a>Category</a>
                <ul>
                    <c:forEach items="${categoriesList}" var="category">
                        <li>
                            <a href="${pageContext.request.contextPath}/gallery?sort=category&value=${category}">${category}</a>
                        </li>
                    </c:forEach>
                </ul>
            </li>
            <li><a href="${pageContext.request.contextPath}/gallery?sort=state&value=Exhibition">Exhibition</a></li>
            <li><a href="${pageContext.request.contextPath}/gallery?sort=state&value=On%20Export">On export</a></li>
        </ul>
    </li>
    <!-- end submenu -->
    <li><a href="${pageContext.request.contextPath}/admin/saveUpdate?id=0">NewExhibit</a></li>
    <li><a href="${pageContext.request.contextPath}/admin/exhibitManagement">Admin panel</a></li>
</ul><!-- close menu -->

<div id="wraper">
    <div id="content"><!-- content -->
        <input type="hidden" id="csrfToken" name="${_csrf.parameterName}"
               value="${_csrf.token}" />
        <ul>
            <c:forEach items="${exhibitList}" var="exhibit">
                <li>
                    <div class="managementedItem" id="exhibitNumber${exhibit.getIdExhibit()}">
                        <div class="leftManagmentContentWraper">
                            <img src="${exhibit.image}" alt="Loading.."/>
                            <div class="leftInnerManagmentContentWraper">
                                <div class="titleExhibit">${exhibit.title}</div>
                                <div class="shortAboutExhibit">${exhibit.about}
                                </div>
                            </div>
                        </div>
                        <hr noshade>
                        <div class="rightManagmentContentWraper">
                            <div class="categoryExhibit">${exhibit.category}</div>
                            <div class="stateExhibit">${exhibit.state}</div>
                            <div class="modifyButton btn btn-info" onclick="ModifyAlert(${exhibit.getIdExhibit()},this)">
                                Modify
                            </div>
                        </div>
                    </div>
                </li>
            </c:forEach>
        </ul>
    </div><!-- end content -->


    <div id="sidebar"><!-- sidebar -->

        <h3>Recent</h3>

        <div class="navcontainer">
            <ul>
                <li><a onclick="getStoredExhibits()">Show only stored exhibits</a></li>
                <li><a onclick="getMuseumExhibits()">Show only exhibits on exhibition</a></li>
                <li><a onclick="getExportExhibits()">Show only export exhibits</a></li>
            </ul>
        </div>
    </div><!-- end sidebar -->
</div>

<div id="footer">
    Exclusively on <a href="http://www.sixrevisions.com">Six Revisions</a> | Created by <a
        href="http://www.csstemplateheaven.com">CssTemplateHeaven</a>
</div>
<%--modal form--%>
<div id="modal_form">
    <span id="modal_close">X</span>
    <div id="modalFormExhibitID"></div>
        <div id="modalFormWraper">
            <div id="modalFormLeftContainer">
                <img id="modalFormImage" src="" alt="Loading.."/>
                <div id="modalFormState" class = "panel panel-warning">
                    <div id="modalFormStateBody" class = "panel-heading">
                    </div>
                </div>
                <div id="modalFormCategory" class = "panel panel-warning">
                    <div id="modalFormCategoryBody" class = "panel-heading">
                    </div>
                </div>
            </div>
                    <div id="modalFormInformationContainer">
                <div id="modalFormTitle" class="titleExhibit"></div>
                <div id="modalFormAbout" class="shortAboutExhibit"></div>
                    </div>
                 <div id="modalFormButtonsContainer">
                     <div id="modalFormButtonsContainerForButtons">
            <div id="modalFormChangeStateButton" class="btn btn-info" onclick="ChangeState()">ChangeState</div>
            <a id="modalFormChangeGeneralInformationButton" href="" class="btn btn-info">Change general information</a>
                         <div id="modalFormChangePLaceButton" class="btn btn-info" onclick="ShowPlaces()">ChangPlace</div>
                     </div>
                     <div id="modalFormButtonsContainerForLists">
                     <div id="modalFormListPLacesContainer" class="list-group">
                         <ul>
                             <c:forEach items="${placeList}" var="place">
                             <li class="list-group-item" onclick="ChangePlace(${place.id_place})">${place.place_name}</li>
                             </c:forEach>
                         </ul>
                     </div>
                     </div>
                 </div>
        </div>
        </div>

    <div id="overlay"></div>

</div>
</body>
</html>

src/main/webapp/WEB-INF/views/gallery.jsp
<%@ page language="java" contentType="text/html; charset=utf-8"
         pageEncoding="ISO-8859-1" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link href="<c:url value='../../resources/css/style.css' />" rel="stylesheet">
    <link href="<c:url value='../../resources/css/bootstrap.css' />" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="../../resources/css/jquery.fancybox-1.3.0.css" media="screen"/>
    <title>${userName}</title>

    <script language="javascript" type="text/javascript"
            src="http://ajax.googleapis.com/ajax/libs/jquery/1.2.6/jquery.min.js"></script>
    <script language="javascript" type="text/javascript"
            src="../../resources/js/Main.js"></script>
</head>
<body>

<div id="header">

    <div id="social">
        <a href="#"><img src="../../resources/styleimages/facebook.png" width="26" height="26" alt="facebook"/></a>
        <a href="#"><img src="../../resources/styleimages/twitter.png" width="26" height="26" alt="twitter"/></a>
        <a href="#"><img src="../../resources/styleimages/linkedin.png" width="26" height="26" alt="linkedin"/></a>
        <a href="#"><img src="../../resources/styleimages/email.png" width="26" height="26" alt="email"/></a>
    </div>

</div>


<ul class="dropdown"><!-- menu -->

    <li><a href="${pageContext.request.contextPath}/">Home</a></li>

    <li><a href="${pageContext.request.contextPath}/gallery">Gallery</a>
        <ul class="sub_menu">
            <li><a>Category</a>
                <ul>
                    <c:forEach items="${categoriesList}" var="category">
                        <li>
                            <a href="${pageContext.request.contextPath}/gallery?sort=category&value=${category}">${category}</a>
                        </li>
                    </c:forEach>
                </ul>
            </li>
            <li><a href="${pageContext.request.contextPath}/gallery?sort=state&value=Exhibition">Exhibition</a></li>
            <li><a href="${pageContext.request.contextPath}/gallery?sort=state&value=On%20Export">On export</a></li>
        </ul>
    </li>
    <!-- end submenu -->
    <li><a href="${pageContext.request.contextPath}/admin/saveUpdate?id=0">NewExhibit</a></li>
    <li><a href="${pageContext.request.contextPath}/admin/exhibitManagement">Admin panel</a></li>
</ul><!-- close menu -->

<div id="gallery"><!-- gallery -->

    <ul>
        <c:if test="${exhibitList.size()==0}">
            <li class="fancybox">
                <img src="../../resources/styleimages/noitems.JPG" style="left: 180%; height: 100%; width: 100%"
                     alt="loading.."/>
            </li>
        </c:if>
        <c:forEach items="${exhibitList}" var="exhibit">
            <li class="fancybox">
                <a href="${pageContext.request.contextPath}/page?id=${exhibit.getIdExhibit()}">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h3 class="panel-title">
                                <c:if test="${exhibit.title.length()>18}">
                                    ${exhibit.title.substring(0,15)}...
                                </c:if>
                                <c:if test="${exhibit.title.length()<18}">
                                    ${exhibit.title}
                                </c:if>
                            </h3>
                        </div>
                        <div class="panel-body">
                            <img class="small-image-gallery" src="${exhibit.image}" width="100px"
                                 height="100px" alt="loading.."/>
                        </div>
                    </div>
                </a>
                <div class="btn-group-vertical">
                    <a href="${pageContext.request.contextPath}/deleteExhibit?id=${exhibit.getIdExhibit()}">
                        <button type="button" class="btn btn-warning">Delete</button>
                    </a>
                    <a href="${pageContext.request.contextPath}/saveUpdate?id=${exhibit.getIdExhibit()}">
                        <button type="button" class="btn btn-success">Update</button>
                    </a>
                </div>
            </li>
        </c:forEach>
    </ul>

</div><!-- close gallery -->


<div id="footer">

</div>

</body>
</html>